### ISSUE TITLE
Static proxy with metadata cache

### ISSUE THREAD

**Issue by akondas** [repman-io/repman#221]
This is the thread where all changes related to the static proxy will be summarized. We give up the solution that downloads metadata files on the fly (no possibility of proper caching).

- [x] remove MetadataProvider and DistStorage from proxy (#222)
- [x] return cache headers in metadata endpoints (#222)
- [x] synchronize metadata files (cli command + cron) (#224)
- [x] make download return stream instead download file to memory (#226)
- [x] use composer v2 endpoints to lookup for distribution (smaller files) (#222)
- [x] replace all file functions with filesystem (this will be base for add support for using S3 as storage, thanks @jonnyynnoj for inspiration) (#223)
- [x] separate proxy logic from private packages (`Proxy` class will encapsulate all) (#223)
- [x] create cli command for renaming dist files in proxy dir (#227)

:warning:  Unfortunately, there will be slight changes that cause a little incompatibility:
- metadata files now will be full json files (previously it was serialized php array)
- dist file will be saved only with reference in name (to reduce storage size)

Upgrading to 0.5.0:
- if you are using migrations (you should) then noting to do :wink:  (thanks to #227)
