### ISSUE TITLE
Release 1.0.0 🚀

### ISSUE THREAD

**Issue by akondas** [repman-io/repman#239]
This is a collective thread for things that need to be done before the official release of `1.0.0`

- [x] maintenance cli command for removing not used dist files for private packages
- [x] logs rotation
- [x] upgrade guide
- [x] atomic deployment with ansible playbook (#241)
- [x] update to Symfony 5.1 :warning: (#248)
- [x] simple REST API (#114, #255 )
- [x] ability to search the package list (#259, thanks to @giggsey)
- [ ] return sha sum for better performance (#261)

**Comment by akondas** [comment]
@karniv00l REST api notes:
- [ ] add help to generate rest api token form
- [ ] add link to docs or some kind of hint in api tokens list
- [ ] add `organization` prefix to all api endpoint with organization param
- [ ] add better response for `PUT api/{organization}/token/{token}` endpoint (maybe just like in create token)
- [ ] add `list` and `create` organization endpoints
